pipeline {
    agent any
    stages {
        stage('Build') {
            agent {
                docker {
                    image 'python:2-alpine'
                }
            }

            steps {
                sh 'python -m py_compile sources/add2vals.py sources/calc.py'
            }
        }
        stage('Test') {
            agent {
                docker {
                    image 'python:3.8'
                }
            }
            steps {
                sh '''
                    python -m venv .venv
                    . .venv/bin/activate
                    pip install pytest
                    pip install allure-pytest
                    pytest sources/test_calc.py --alluredir=./my_allure_results
                '''
            }
            post {
                always {
                    stash includes: 'my_allure_results/*.json', name: 'app'
                }
            }
        }
    }
    post { 
        always { 
                unstash 'app'
                script {
                        allure([
                                includeProperties: false,
                                jdk: '',
                                properties: [],
                                reportBuildPolicy: 'ALWAYS',
                                results: [[path: 'my_allure_results']]
                        ])
                }
        }
    }
}
